### PR TITLE
feat(view): Option to show/hide completed tasks

### LINKED ISSUE #52: Hide completed tasks in a view
Add an option to hide completed tasks in a view

### PR DESCRIPTION
**Pull request by Us3r-gitHub**
Closes #52 

TODO:
- [x] Update migration

### CODE REVIEW

**Comment by MoShizzle** [comment]
I think for this, having the hide completed chip add a filter to the view would be a better option, since the user would expect completed cards to always not show, regardless of which grouping option is set.

**Comment by Us3r-gitHub** [comment]
> I think for this, having the hide completed chip add a filter to the view would be a better option, since the user would expect completed cards to always not show, regardless of which grouping option is set.

Do you mean that we don't need a toggle for 'hide completed,' but we should add it to the filter chip instead?

**Comment by MoShizzle** [comment]
> > I think for this, having the hide completed chip add a filter to the view would be a better option, since the user would expect completed cards to always not show, regardless of which grouping option is set.
> 
> Do you mean that we don't need a toggle for 'hide completed,' but we should add it to the filter chip instead?

No we need a toggle for it, but the toggle should affect the cards data not just the list data. with the current solution, if I group cards by assignee how will we know which cards are completed? Since the groups don't have the isCompleted flag. Don't you think it would be better to have it as a param for the cardsService findAll function in the backend?

**Comment by Us3r-gitHub** [comment]
> Don't you think it would be better to have it as a param for the cardsService findAll function in the backend?

Since the isCompleted flag is currently embedded in the ListStage table, 
If we add it as a parameter in the CardsService, how should we manage it?
Should our concern primarily be within the ListStage context?

**Comment by Us3r-gitHub** [comment]
I'd like to discuss our approach to handling this function.
Currently, we use ListGroupSModule for this purpose. However, I'm considering whether it would be more effective to manage this in a ListSModule. 

What do you think about this approach?
For example, we can pass a `group` as a parameter then it will be processed further in the ListGroupModule.

**Comment by Us3r-gitHub** [comment]
> Don't you think it would be better to have it as a param for the cardsService findAll function in the backend?

I've just understood your point, and I've implemented it in this commit [6ce31cf](https://github.com/tillywork/tillywork/pull/93/commits/6ce31cf95895cd9b26c9a61d1ae2de814bf554cc)

Thank you

**Comment by Us3r-gitHub** [comment]
image

Hi, although users can include completed tasks into the view, I think we need to differentiate them more clearly.
Do you have any suggestions on how we can make it easier to distinguish completed tasks from others?

**Comment by MoShizzle** [comment]
> image
> 
> Hi, although users can include completed tasks into the view, I think we need to differentiate them more clearly. Do you have any suggestions on how we can make it easier to distinguish completed tasks from others?

I agree on this point, can you open a new issue for this?

**Comment by Us3r-gitHub** [comment]
> Can you open a new issue for this?

I will create it now

Additionally, could you advise me on the criteria that should determine when to split a current issue instead of working on it as is? :)

**Comment by MoShizzle** [comment]
> > Can you open a new issue for this?
> 
> I will create it now
> 
> Additionally, could you advise me on the criteria that should determine when to split a current issue instead of working on it as is? :)

Basically if the issue is not directly related to the current working issue, we split it. Usually PRs or issues should only tackle 1 topic only, there are exceptions of course for larger features but this is generally what we do 😄

**Review by MoShizzle — APPROVED** [review]

**Pull request merged**
