### PR TITLE
Enhancement: Color Picker Swatches

### PR DESCRIPTION
**Pull request by codonade**
Pick a color from a collection of built-in ones acting as a mini color palette for Tillywork.

Screenshot 2024-06-22 111804

### CODE REVIEW

**Comment by codonade** [comment]
What do you think of this?

**Comment by Us3r-gitHub** [comment]
Using both seems excessive, we have to choose just one.

Additionally, I think we can enhance it with theme variables.
For example, the default could be referenced as #ffffff, and primary as #1976D2, etc

**Comment by codonade** [comment]
> I think using both seems excessive, we can choose just one.

> Yeah you're probably right. What do you think should we keep? The HEXA picker gives users the most customizability, while the swatches make it easier for them to have consistent colors across their workspaces.

> Additionally, I think we can enhance it with theme variables.

This is already implemented in the original component. In the text field, you can type theme variables and the color will get picked up automatically, although not all of  these variables are mapped to the swatches. But personally, the more I think about this, the less convinced am I with it. When users think about color, they usually think in `red`, `green`, and `blue`, not in `error`, `succes`, and `primary`

**Comment by Us3r-gitHub** [comment]
In my opinion, swatches are the best option
maybe there are suggestions from others

> When users think about color, they usually think in `red`, `green`, and `blue`.

It will solve this too.

**Comment by codonade** [comment]
> In my opinion, swatches are the best option

That's also what I think.

**Review by MoShizzle — APPROVED** [review]

**Pull request merged**
