### PR TITLE
Feature: Post-login Navigation

### LINKED ISSUE #43: Post-login navigation
The user should never be on an empty page. We should always redirect the user after login to their last opened list or the first list if none exists.

### PR DESCRIPTION
**Pull request by codonade**
Resolves #43

### CODE REVIEW

**Comment by codonade** [comment]
Would it be beneficial to move the redirection logic to the `index.vue` page? That way we can navigate the users to their last opened list (or, if my [suggestion](https://github.com/tillywork/tillywork/issues/43#issuecomment-2143520137) gets implemented, to their "startup list") whenever they specifically visit the index page `/`, not just when they get redirected to it upon login.

**Comment by Us3r-gitHub** [comment]
> Would it be beneficial to move the redirection logic to the `index.vue` page?
I agree with you; it should be there.
Waiting for other developers' responses.

**Comment by MoShizzle** [comment]
> Would it be beneficial to move the redirection logic to the `index.vue` page? That way we can navigate the users to their last opened list (or, if my [suggestion](https://github.com/tillywork/tillywork/issues/43#issuecomment-2143520137) gets implemented, to their "startup list") whenever they specifically visit the index page `/`, not just when they get redirected to it upon login.

Yes you are correct, this behavior should not be specific to only logging in, let's move it to the index page instead

**Comment by codonade** [comment]
> let's move it to the index page instead

I'll get working on this.

**Pull request merged**
