### PR TITLE
Feature: Update Workspaces, Spaces, Lists, and Views "Settings"

### LINKED ISSUE #84: Renaming Spaces, Lists, and Workspaces
Currently, the only way to rename spaces, lists, and workspaces is to delete and recreate them with the desired name - not very intuitive if you ask me. I think we should have - besides the "Delete" action - a "Rename" action, which does exactly what it says.

### PR DESCRIPTION
**Pull request by codonade**
Resolves #84 and, thanks to the upsertion dialogs, introduces the ability to update and change settings of the mentioned items in addition to views, which weren't mentioned originally. #90 was discovered while working on this feature.

### CODE REVIEW

**Comment by codonade** [comment]
1. I made the rename popovers accessible via a different button rather than from menus; thought this made the act of renaming easier and faster, especially for people like me who rename their stuff thousand times a second 😁 Would you like to also add the rename action to menus next to the delete one?
2. Renaming views is done via their settings popover rather than a separate popover like the other items. This was because of #86; I think that having all the things related to the view in one popover is much better, and the settings popover allows to collocate the stages show/hide settings with the renaming stuff in one place. What do you think of this? Also, the behavior of the views settings popover is temporary because I don't like it. What would you suggest?

**Comment by MoShizzle** [comment]
> 1. I made the rename popovers accessible via a different button rather than from menus; thought this made the act of renaming easier and faster, especially for people like me who rename their stuff thousand times a second 😁 Would you like to also add the rename action to menus next to the delete one?

I like how this looks, but let's remove it from workspaces, and also add it to the settings menus

>     2. Renaming views is done via their settings popover rather than a separate popover like the other items. This was because of [Hide List Stages in specific View #86](https://github.com/tillywork/tillywork/issues/86); I think that having all the things related to the view in one popover is much better, and the settings popover allows to collocate the stages show/hide settings with the renaming stuff in one place once the first get implemented. What do you think of this? Note that I hate the way I implemented the settings popover with; I just wanted to prototype and see how it goes, so any suggestions on it are welcome.

I think it would be better to convert the current create dialogs for lists/views/etc.. into upsertion dialogs, where you can use the same dialog to create/edit entities, since that would make it easier to maintain.

Also, make sure to use v-forms with validation rules for any edit/create actions we have.

**Comment by MoShizzle** [comment]
> > I like how this looks, but let's remove it from workspaces, and also add it to the settings menus
> 
> So you want the user to rename workspaces from the settings menu, not from the navigation drawer?

Yes

> > I think it would be better to convert the current create dialogs for lists/views/etc.. into upsertion dialogs,
> 
> Would you like me to replace the popovers I've made with the upsertion dialogs?

Yes, check https://github.com/tillywork/tillywork/blob/main/packages/frontend/src/components/common/dialogs/UpsertListStageDialog.vue for reference

**Comment by codonade** [comment]
> Yes, check https://github.com/tillywork/tillywork/blob/main/packages/frontend/src/components/common/dialogs/UpsertListStageDialog.vue for reference

That's why I merged 😁

**Review by MoShizzle — APPROVED** [review]

**Pull request merged**
